import {SceneMap,SceneMarker} from './scene-map';
import type {Coord,WalkResult} from './types';
import {meters} from './routing';
import {bbox,booleanPointInPolygon,point,pointToLineDistance} from '@turf/turf';
import {accepts,closureFeature,wasteTypes,safeSourceUrl} from './extra-data';
type Snapshot={title:string;url:string;resource:string;resourceModified:string|null;catalogModified:string;retrieved:string;data:any};
type Service={id:string;coordinates:Coord;name:string;kind:string;properties:Record<string,any>};
const empty={type:'FeatureCollection',features:[]};const collection=(features:any[])=>({type:'FeatureCollection',features});
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(v:string|null)=>v?new Date(/(?:Z|[+-]\d\d:\d\d)$/.test(v)?v:v+'Z').toLocaleString('hr-HR'):'Nije naveden';
const labels:Record<string,string>={closures:'Zatvorene prometnice',toilets:'Javni WC-i',recycling:'Reciklažna dvorišta',underground:'Podzemni spremnici',semiburied:'Polupodzemni spremnici',landuse:'Planirana namjena · 2023.',brownfield:'Brownfield površine'};
const colors:Record<string,string>={closures:'#d65c4f',toilets:'#496eb5',recycling:'#42876c',underground:'#42876c',semiburied:'#42876c',landuse:'#bb9958',brownfield:'#a5679a'};

export class ExtraLayers {
 private snapshots=new Map<string,Snapshot>();private services:Service[]=[];private enabled=new Set<string>();private markers=new Map<string,SceneMarker>();private origin:Coord;private minutes=10;private result:WalkResult|null=null;private mode='toilets';private waste='';private panel:HTMLElement;private detail:HTMLElement;private warning='';private roads:any[]=[];private areaFeatures:any[]=[];private ready=false;private areaCache=new Map<string,{feature:any;bounds:number[]}[]>();private busy=false;private drawKey='';private visibleServices:Service[]=[];
 constructor(private map:SceneMap,origin:Coord,private route:(id:string)=>void){this.origin=origin;
  this.panel=document.createElement('section');this.panel.className='extra-section';this.panel.innerHTML=`<details id="extra-tools"><summary>Svakodnevno i planovi <span>NOVO</span></summary><p class="muted small">Odaberi sadržaj ili prostorni sloj.</p><div class="extra-buttons">${['toilets','recycling','closures','landuse','brownfield'].map(k=>`<button data-extra="${k}" aria-pressed="false">${labels[k]}</button>`).join('')}</div><div id="extra-content"></div></details>`;document.getElementById('district-link')!.before(this.panel);
  const entry=document.createElement('button');entry.className='text-button';entry.textContent='Svakodnevno i planovi →';entry.onclick=()=>{(this.panel.querySelector('details') as HTMLDetailsElement).open=true;document.getElementById('sidebar')!.classList.add('mobile-open');document.getElementById('layers-panel')!.hidden=true;this.panel.scrollIntoView({block:'start',behavior:'smooth'});};document.getElementById('layers-panel')!.append(entry);
  this.detail=document.createElement('div');this.detail.className='detail-card extra-detail';this.detail.hidden=true;this.detail.setAttribute('aria-live','polite');document.querySelector('.map-section')!.append(this.detail);
  this.panel.querySelectorAll<HTMLButtonElement>('[data-extra]').forEach(b=>b.onclick=()=>{this.mode=b.dataset.extra!;this.warning='';if(this.enabled.has(this.mode)){this.enabled.delete(this.mode);this.hideDetails();}else this.enabled.add(this.mode);this.refresh();if(this.mode==='closures'&&this.enabled.has('closures'))void this.refreshClosures();});
  for(const id of ['extra-closures','extra-landuse','extra-brownfield','extra-selected']){this.map.addSource(id,{data:empty});this.map.addLayer({id,type:id==='extra-landuse'||id==='extra-brownfield'?'fill':'line',source:id,paint:{'fill-color':id==='extra-landuse'?'#bdac68':'#b378a0','fill-opacity':.4,'line-color':id==='extra-closures'?'#e45545':'#f0a22b'}});}
  this.map.on('moveend',()=>this.refresh());setInterval(()=>{if(this.enabled.has('closures')&&!document.hidden)void this.refreshClosures();},180000);
  void this.load();
 }
 private async load(){try{const keys=['toilets','recycling','underground','semiburied','closures'];await Promise.all(keys.map(async k=>{this.snapshots.set(k,await this.fetchJson('extra-'+k));}));this.services=await this.fetchJson('extra-services');this.roads=this.snapshots.get('closures')!.data.map(closureFeature).filter(Boolean);this.ready=true;this.refresh();}catch{this.panel.querySelector('#extra-content')!.innerHTML='<p class="notice">Dodatni podaci nisu učitani. <button id="extra-retry">Pokušaj ponovno</button></p>';this.panel.querySelector('#extra-retry')?.addEventListener('click',()=>void this.load());}}
 private async fetchJson(name:string){const r=await fetch(import.meta.env.BASE_URL+'data/'+name+'.json');if(!r.ok)throw Error(name);return r.json();}
 hideDetails(){this.detail.hidden=true;this.map.getSource('extra-selected').setData(empty);}
 update(origin:Coord,minutes:number,result:WalkResult|null){this.origin=origin;this.minutes=minutes;this.result=result;if(this.ready)this.refresh();}
 private async area(key:string){if(this.snapshots.has(key)||this.busy)return;this.busy=true;try{const s:Snapshot=await this.fetchJson('extra-'+key);this.snapshots.set(key,s);this.areaCache.set(key,s.data.features.map((feature:any)=>({feature,bounds:bbox(feature)})));}catch{this.warning='Prostorni sloj nije učitan. Isključi i ponovno uključi sloj za novi pokušaj.';}finally{this.busy=false;this.refresh();}}
 private stamp(key:string){const s=this.snapshots.get(key);return s?`<p class="extra-stamp">Preuzeto: ${esc(date(s.retrieved))}<br/>Izmjena resursa: ${esc(date(s.resourceModified))}${!s.resourceModified?`<br/>Izmjena kataloga: ${esc(date(s.catalogModified))}`:''}<br/>Datum izmjene ne jamči stanje na terenu.</p>`:'';}
 private refresh(){if(!this.ready)return;
  this.panel.querySelectorAll<HTMLButtonElement>('[data-extra]').forEach(b=>{const on=this.enabled.has(b.dataset.extra!);b.setAttribute('aria-pressed',String(on));b.classList.toggle('active',on);});
  const content=this.panel.querySelector<HTMLElement>('#extra-content')!;const kind=this.mode;let html='';
  if(!this.enabled.has(kind))html='<p class="muted small">Sloj je isključen. Klikni naziv da ga prikažeš.</p>';
  else if(kind==='toilets'||kind==='recycling'){
   const isWaste=kind==='recycling';const items=this.services.filter(s=>isWaste?(this.waste?s.kind==='recycling'&&accepts(s.properties[this.waste]):s.kind!=='toilets'):s.kind==='toilets').sort((a,b)=>(this.result?.distances[a.id]??Infinity)-(this.result?.distances[b.id]??Infinity)||meters(this.origin,a.coordinates)-meters(this.origin,b.coordinates));
   html=(isWaste?`<label class="extra-filter">Vrsta otpada<select id="waste-filter"><option value="">Sva mjesta i spremnici</option>${Object.entries(wasteTypes).map(([k,v])=>`<option value="${k}" ${k===this.waste?'selected':''}>${v}</option>`).join('')}</select></label><p class="muted small">Za odabrani otpad prikazujemo samo dvorišta koja u izvoru potvrđuju prihvat. Za spremnike vrste otpada nisu potvrđene.</p>`:'')+`<p class="muted small">${items.filter(s=>this.result?.distances[s.id]!==undefined).length} lokacija s putem u ${this.minutes} min. Prikazujemo do 20 najbližih; ostale mogu biti izvan dosega.</p>`+items.slice(0,20).map(s=>`<button class="extra-result" data-service="${s.id}"><strong>${esc(s.name)}</strong><span>${esc(s.properties.ADRESA_LOK||s.properties.adresa||s.properties.adrese||labels[s.kind])}</span><small>${this.result?.distances[s.id]!==undefined?this.result.distances[s.id]+' min hoda':Math.round(meters(this.origin,s.coordinates))+' m zračno · bez puta u odabranom dosegu'}</small></button>`).join('');
   this.visibleServices=items;
  }else if(kind==='closures'){
   const near=this.nearRoads();html=`<p class="notice small">Zatvaranje za vozila ne znači nužno zatvaranje za pješake. Izračun hoda ne mijenjamo.</p><button id="refresh-closures" class="text-button">Osvježi prometnice</button>${this.warning?`<p class="notice small">${esc(this.warning)}</p>`:''}<p class="muted small">${near.length} zatvorenih dionica do 2 km od polazišta.</p>`+near.map(f=>`<button class="extra-result" data-road="${f.properties.id}"><strong>${esc(f.properties.street||'Prometnica')}</strong><small>Očekivani završetak: ${esc(date(f.properties.expectedEndTime))}</small></button>`).join('');
  }else{
   if(!this.snapshots.has(kind)){if(!this.warning)void this.area(kind);html=`<p class="muted small">${this.warning?esc(this.warning):'Učitavanje prostornih podataka…'}</p>`;}
   else html=`<p class="notice small">${kind==='landuse'?'Planirana namjena prema dokumentaciji iz 2023. Nije potvrda današnjih uvjeta gradnje ni najava projekta. Boje označavaju skupnu namjenu.':'Evidentirane zapuštene ili nedovoljno korištene površine. Nisu nužno aktivni gradski projekti.'}</p><p class="muted small">Približi kartu i klikni obojenu površinu za podatke. Prikazujemo obuhvate u okolini središta karte.</p>${kind==='landuse'?'<div class="landuse-legend"><span>🟩 Zelenilo / poljoprivreda / šume</span><span>🟨 Stanovanje</span><span>🟧 Mješovita namjena</span><span>🟦 Javna / društvena namjena</span><span>🟪 Gospodarska namjena</span><span>◻ Ostalo</span></div>':''}`;
  }
  content.innerHTML=html+this.stamp(kind);content.querySelector<HTMLSelectElement>('#waste-filter')?.addEventListener('change',e=>{this.waste=(e.target as HTMLSelectElement).value;this.refresh();});content.querySelector('#refresh-closures')?.addEventListener('click',()=>void this.refreshClosures());content.querySelectorAll<HTMLElement>('[data-service]').forEach(b=>b.onclick=()=>this.showService(this.services.find(s=>s.id===b.dataset.service)!));content.querySelectorAll<HTMLElement>('[data-road]').forEach(b=>b.onclick=()=>this.showRoad(this.roads.find(f=>String(f.properties.id)===b.dataset.road)));
  this.draw();
 }
 private nearRoads(){return this.roads.filter(f=>pointToLineDistance(point(this.origin),f,{units:'meters'})<=2000);}
 private draw(){const c=this.map.getCenter();const key=[...this.enabled,this.waste,c.lng.toFixed(4),c.lat.toFixed(4),this.map.getZoom().toFixed(2),...this.map.camera.quaternion.toArray().map(n=>n.toFixed(3)),this.snapshots.get('closures')?.retrieved,...this.areaCache.keys()].join('|');if(key===this.drawKey)return;this.drawKey=key;const keep=new Set<string>();
  for(const s of [...this.services].sort((a,b)=>meters(this.origin,a.coordinates)-meters(this.origin,b.coordinates))){if(!(s.kind==='toilets'?this.enabled.has('toilets'):this.enabled.has('recycling'))||this.waste&&s.kind!=='toilets'&&!(s.kind==='recycling'&&accepts(s.properties[this.waste]))||!this.map.getBounds().contains(s.coordinates)||this.map.getZoom()<13)continue;if(keep.size>=60)break;keep.add(s.id);if(!this.markers.has(s.id)){const el=document.createElement('button');el.className='poi-marker';el.style.setProperty('--pin',colors[s.kind]);el.textContent=s.kind==='toilets'?'WC':'♻';el.setAttribute('aria-label',s.name);el.onclick=e=>{e.stopPropagation();this.showService(s);};this.markers.set(s.id,new SceneMarker({element:el}).setLngLat(s.coordinates).addTo(this.map));}}
  for(const [id,m]of this.markers)if(!keep.has(id)){m.remove();this.markers.delete(id);}
  this.map.getSource('extra-closures').setData(collection(this.enabled.has('closures')?this.roads:[]));
  this.areaFeatures=[];const center=this.map.getCenter();for(const key of ['landuse','brownfield']){const list=this.enabled.has(key)&&this.map.getZoom()>=12?(this.areaCache.get(key)||[]).filter(({bounds:b})=>b[0]<center.lng+.035&&b[2]>center.lng-.035&&b[1]<center.lat+.025&&b[3]>center.lat-.025).slice(0,1800).map(({feature:f})=>({...f,properties:{...f.properties,extraKind:key,displayColor:this.landColor(f.properties)}})):[];this.areaFeatures.push(...list);this.map.getSource('extra-'+key).setData(collection(list));}
 }
 private landColor(p:any){const s=String(p.Skupna_namjena||p.Namjena||'').toLowerCase();return /zelen|šum|poljopriv|park/.test(s)?'#7ea67c':/mješovit/.test(s)?'#d9a56a':/stamb/.test(s)?'#e2cf82':/javn|društven/.test(s)?'#799dc4':/gospodar|poslov|industr/.test(s)?'#b090bb':'#bac3bf';}
 handleClick(c:Coord){for(const f of [...this.areaFeatures].reverse())if(booleanPointInPolygon(point(c),f)){this.showArea(f);return true;}if(this.enabled.has('closures')){const f=this.roads.find(f=>pointToLineDistance(point(c),f,{units:'meters'})<25);if(f){this.showRoad(f);return true;}}return false;}
 private show(title:string,body:string,key:string){document.getElementById('detail-card')!.hidden=true;this.detail.hidden=false;this.detail.innerHTML=`<button class="detail-close icon-button" aria-label="Zatvori dodatne detalje">×</button><span class="eyebrow">${labels[key]}</span><h2>${esc(title)}</h2>${body}${this.stamp(key)}<a href="${esc(this.snapshots.get(key)!.url)}" target="_blank" rel="noopener">Službeni izvor ↗</a>`;this.detail.querySelector('button')!.onclick=()=>{this.detail.hidden=true;this.map.getSource('extra-selected').setData(empty);};}
 private fields(p:any,fields:Record<string,string>){return '<dl>'+Object.entries(fields).map(([key,label])=>`<div><dt>${label}</dt><dd>${esc(p[key]??'Nije objavljeno')}</dd></div>`).join('')+'</dl>';}
 private showService(s:Service){const p=s.properties,time=this.result?.distances[s.id];this.map.easeTo({center:s.coordinates,duration:600});this.show(s.name,this.fields(p,s.kind==='toilets'?{adresa:'Adresa',naplata:'Naplata'}:s.kind==='recycling'?{ADRESA_LOK:'Adresa',RADNO_VRIJ:'Objavljeno radno vrijeme',TELEFON:'Telefon'}:{adrese:'Adresa',Status:'Status',status:'Status u izvoru',Spremnik:'Spremnik'})+(s.kind==='recycling'?`<p>Potvrđen prihvat: ${Object.entries(wasteTypes).filter(([k])=>accepts(p[k])).map(([,v])=>v).join(', ')||'Nije naveden'}</p>`:'')+`<p>${time!==undefined?time+' min hoda od polazišta.':'Nema izračunatog puta unutar odabranog vremena.'}</p><button class="extra-route">Prikaži pješački put</button><p class="muted small">Put može biti dulji od odabranog vremena dostupnosti.</p>`,s.kind);this.detail.querySelector('.extra-route')?.addEventListener('click',()=>this.route(s.id));}
 private showRoad(f:any){const p=f.properties;this.map.getSource('extra-selected').setData(collection([f]));this.show(p.street||'Zatvorena prometnica',`<p>${p.subtype==='ROAD_CLOSED_CONSTRUCTION'?'Zatvoreno zbog radova':esc(p.subtype||'Razlog nije naveden')}</p><p>${p.direction==='BOTH_DIRECTIONS'?'Oba smjera':p.direction==='ONE_DIRECTION'?'Jedan smjer':esc(p.direction)}</p><p>Očekivani početak: ${date(p.expectedStartTime)}<br/>Očekivani završetak: ${date(p.expectedEndTime)}</p>${Date.parse(p.expectedEndTime)<Date.now()?'<p class="notice">Navedeni rok je prošao; zapis u izvoru nije potvrda ponovnog otvaranja.</p>':''}<p class="notice small">Prometno ograničenje ne potvrđuje neprohodnost pješačkog puta.</p>`,'closures');}
 private showArea(f:any){const key=f.properties.extraKind,p=f.properties;this.map.getSource('extra-selected').setData(collection([f]));this.show(p.Naziv||p.Namjena||'Planirana površina',this.fields(p,key==='landuse'?{Namjena:'Namjena',Skupna_namjena:'Skupna namjena',Analitika:'Dodatna oznaka',Naziv_plana:'Naziv plana',Godina_zadnje_izmjene:'Godina izmjene u zapisu'}:{Prethodno_koristenje:'Prethodno korištenje',Privremeno_korištenje:'Privremeno korištenje',Oznaka_planske_namjene:'Planska namjena',Status_UPUa:'Status UPU-a',Obveza_izrade_UPUa:'Obveza izrade UPU-a'})+`<p class="notice small">${key==='landuse'?'Stanje dokumentacije iz 2023.; nije potvrda aktualnih uvjeta gradnje.':'Obuhvat nije potvrda planiranog ili aktivnog ulaganja.'}</p>`+(safeSourceUrl(p.Poveznica)?`<p><a href="${esc(safeSourceUrl(p.Poveznica))}" target="_blank" rel="noopener">Dokumentacija iz zapisa ↗</a></p>`:''),key);}
 private async refreshClosures(){const s=this.snapshots.get('closures');if(!s)return;try{const r=await fetch(import.meta.env.BASE_URL+'live/closures.json',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data))throw Error();this.roads=data.map(closureFeature).filter(Boolean);s.data=data;s.retrieved=new Date().toISOString();s.resourceModified=r.headers.get('last-modified')?new Date(r.headers.get('last-modified')!).toISOString():null;this.warning='';}catch{this.warning='Osvježavanje nije uspjelo. Prikazana je posljednja dohvaćena snimka, prema datumu ispod.';}this.refresh();}
}
