import {SceneMap,SceneMarker} from './scene-map';
import {ExtraLayers} from './extras';
let extras:ExtraLayers|undefined;
import {createIcons, Search, MapPin, ArrowUpRight, ArrowRight, ChevronRight, ChevronDown, X, Plus, Minus, Navigation, LocateFixed, Layers, Footprints, TrainFront, Baby, GraduationCap, HeartPulse, Trees, Bike, Landmark, Store, Dumbbell, Droplets, CircleHelp, SlidersHorizontal, Check, Construction, Clock3, ChartNoAxesCombined, UsersRound, PersonStanding, Info, ExternalLink, RotateCcw, Menu, CheckCheck} from 'lucide';
import {bbox, convex, featureCollection, point, pointOnFeature, booleanPointInPolygon} from '@turf/turf';
import type {FeatureCollection, Feature, Geometry} from 'geojson';
import type {Amenity,Project,Coord,District,WalkResult} from './types';
import {meters} from './routing';
import './style.css';
const asset=(path:string)=>import.meta.env.BASE_URL+path;
const icons={Search,MapPin,ArrowUpRight,ArrowRight,ChevronRight,ChevronDown,X,Plus,Minus,Navigation,LocateFixed,Layers,Footprints,TrainFront,Baby,GraduationCap,HeartPulse,Trees,Bike,Landmark,Store,Dumbbell,Droplets,CircleHelp,SlidersHorizontal,Check,Construction,Clock3,ChartNoAxesCombined,UsersRound,PersonStanding,Info,ExternalLink,RotateCcw,Menu,CheckCheck};
const icon=(name:string,cls='')=>`<i data-lucide="${name}" class="${cls}"></i>`;
const refreshIcons=()=>createIcons({icons,attrs:{'stroke-width':1.7}});
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const number=(n:number)=>new Intl.NumberFormat('hr-HR').format(n);
const money=(n:number|null)=>n===null?'Nije objavljeno':new Intl.NumberFormat('hr-HR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const compactMoney=(n:number)=>n>=1e6?(n/1e6).toLocaleString('hr-HR',{maximumFractionDigits:1})+' mil. €':money(n);
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const empty:FeatureCollection={type:'FeatureCollection',features:[]};
const categories=[
 {id:'transport',name:'Javni prijevoz',icon:'train-front',color:'#426ad5'},
 {id:'nursery',name:'Dječji vrtići',icon:'baby',color:'#bd8b35'},
 {id:'school',name:'Škole',icon:'graduation-cap',color:'#af8544'},
 {id:'health',name:'Zdravstvo',icon:'heart-pulse',color:'#ca6c75'},
 {id:'park',name:'Parkovi i zelenilo',icon:'trees',color:'#4f9270'},
 {id:'sport',name:'Sport i rekreacija',icon:'dumbbell',color:'#6c91a5'},
 {id:'culture',name:'Kultura',icon:'landmark',color:'#8e74b5'},
 {id:'market',name:'Tržnice',icon:'store',color:'#bf8063'},
 {id:'bike',name:'Biciklistička infrastruktura',icon:'bike',color:'#548f98'},
 {id:'water',name:'Javni zdenci',icon:'droplets',color:'#648fb5'}
];
const statusNames:Record<string,string>={planned:'Planirano',active:'U tijeku',completed:'Završeno',stalled:'Zastoj',unknown:'Status nije objavljen'};
let amenities:Amenity[]=[],projects:Project[]=[],districts:FeatureCollection=empty,sources:any,streets:any[]=[],buildIndex:any[]=[];
let origin:Coord=[15.97355,45.80682],locationName='Trg Petra Svačića',districtName='Donji grad',minutes=10,profile='all',view='nearby',statusFilter='all',includeArchive=false,selectedCategory:string|null=null;
let activeCategories=new Set(categories.map(c=>c.id));let result:WalkResult|null=null,requestId=0,workerReady=false,mapReady=false,cityMode=false,cityMetric='density';
let map:SceneMap;const markers=new Map<string,SceneMarker>();let homeMarker:SceneMarker;let worker:Worker;let dataReady=false;let showProjects=true;let modalFocus:HTMLElement|null=null;
const app=$('app');
app.innerHTML=`
<header class="topbar">
 <a class="brand" href="${asset('')}" aria-label="Moj Zagreb početna"><img src="${asset('favicon.svg')}" alt=""/><span>Moj Zagreb<span class="brand-dot">.</span></span><span class="beta">BETA</span></a>
 <nav aria-label="Glavna navigacija"><button class="nav-item active" id="explore-nav">Istraži svoj kvart</button><button class="nav-item" id="compare-nav">Usporedi četvrti ${icon('arrow-up-right')}</button></nav>
 <div class="header-right"><span class="open-data"><span class="live-dot"></span>Grad otvorenih podataka</span><button class="icon-button" id="help-button" aria-label="Kako koristiti kartu">${icon('circle-help')}</button><button class="source-link" id="sources-button">O podacima ${icon('arrow-up-right')}</button><button class="icon-button mobile-menu" id="mobile-menu" aria-label="Otvori ili zatvori pregled kvarta">${icon('menu')}</button></div>
</header>
<main class="workspace">
 <aside class="sidebar" id="sidebar">
  <div class="sidebar-top"><div class="eyebrow">ZAGREB, IZ TVOJE PERSPEKTIVE</div><h1>Tvoj grad.<br/>Na dohvat koraka.</h1><p class="intro">Vidi što ti je blizu. <br/>Otkrij što se u tvom kvartu mijenja.</p>
   <div class="search-wrap">${icon('search')}<input id="search" type="search" placeholder="Pronađi ulicu, kvart ili sadržaj" aria-label="Pretraži ulice, četvrti i javne sadržaje" autocomplete="off" role="combobox" aria-expanded="false" aria-controls="search-results"/><kbd>⌘ K</kbd><div id="search-results" class="search-results" role="listbox" hidden></div></div>
   <div class="view-tabs" role="tablist" aria-label="Pogled na kvart"><button class="active" id="nearby-tab" role="tab" aria-selected="true">${icon('footprints')}Dostupno u blizini</button><button id="projects-tab" role="tab" aria-selected="false">${icon('construction')}Grad u mom kvartu</button></div>
  </div>
  <div class="sidebar-content" id="sidebar-content">
   <section class="walk-section"><div class="section-heading"><h2>Koliko daleko želiš prošetati?</h2>${icon('footprints')}</div><div class="time-selector" aria-label="Vrijeme hoda">${[5,10,15].map(n=>`<button data-minutes="${n}" class="${n===minutes?'active':''}" aria-pressed="${n===minutes}"><strong>${n}</strong> min</button>`).join('')}</div><div class="pace"><span>Laganim korakom</span><span>4,8 km/h ${icon('info')}</span></div></section>
   <section class="profile-section"><div class="section-heading"><h2>Moj pogled</h2><button class="text-button" id="profile-info" aria-label="Objašnjenje osobnih pogleda">${icon('info')}</button></div><div class="profile-pills"><button class="active" data-profile="all">${icon('person-standing')}Svi sadržaji</button><button data-profile="family">${icon('users-round')}Obitelj</button><button data-profile="carfree">${icon('train-front')}Bez auta</button><button data-profile="bike">${icon('bike')}Biciklist</button></div></section>
   <section id="availability-section"><div class="section-heading"><h2>U <span id="minutes-label">10</span> minuta hoda</h2><span class="small-label" id="amenity-total">Učitavanje…</span></div><div id="categories" class="category-list"></div><div id="amenity-list" hidden></div></section>
   <div class="score-card" id="score-card"><div><span class="eyebrow">DOSTUPNOST SADRŽAJA</span><span class="experimental">Eksperimentalno</span></div><div class="score-main"><div class="score-value" id="score-value">—<span>/ 100</span></div><div><strong id="score-title">Upoznaj svoju okolinu</strong><p id="score-description">Računamo putove od tvoje lokacije.</p></div></div><div class="score-track"><span id="score-bar"></span></div><button class="text-button" id="method-button">Kako računamo indeks? ${icon('arrow-up-right')}</button></div>
   <div id="project-list-panel" hidden></div>
   <button class="district-link" id="district-link"><span class="district-icon">${icon('chart-no-axes-combined')}</span><span><strong>A kako stoje drugi kvartovi?</strong><small>Usporedi svih 17 gradskih četvrti</small></span>${icon('arrow-up-right')}</button>
  </div>
  <footer class="sidebar-footer"><span class="live-dot"></span><button id="snapshot-button">Službeni podaci. Otvoren pogled.</button>${icon('arrow-up-right')}</footer>
 </aside>
 <section class="map-section" aria-label="Interaktivna 3D karta Zagreba">
  <div id="map"></div>
  <div class="map-topline"><div class="breadcrumb"><span class="city-symbol">${icon('map-pin')}</span><span>Zagreb</span><span class="slash">/</span><strong id="district-breadcrumb">Donji grad</strong><button id="district-picker" aria-label="Odaberi gradsku četvrt">${icon('chevron-down')}</button></div><button class="map-chip" id="mountain-view" title="Pogled na Zagreb i Medvednicu">ZG3D · LoD 2.2<span class="chip-divider"></span>Medvednica ↗</button></div>
  <div class="map-instruction" id="map-instruction">${icon('map-pin')}Klikni zgradu i istraži svoju okolinu<button id="dismiss-tip" aria-label="Sakrij uputu">${icon('x')}</button></div>
  <aside class="projects-float" id="projects-float"></aside>
  <div class="map-tools"><button class="compass" id="north-button" aria-label="Okreni kartu prema sjeveru"><span>N</span>${icon('navigation')}</button><div class="tool-group"><button id="zoom-in" aria-label="Približi kartu">${icon('plus')}</button><button id="zoom-out" aria-label="Udalji kartu">${icon('minus')}</button></div><button class="tool" id="locate-button" aria-label="Koristi moju lokaciju">${icon('locate-fixed')}</button><button class="tool selected" id="dimension-button" aria-label="Prebaci na 2D prikaz">3D</button><button class="tool" id="layers-button" aria-label="Postavke slojeva">${icon('layers')}</button></div>
  <div class="layers-panel" id="layers-panel" hidden><strong>Slojevi karte</strong><label><input type="checkbox" id="buildings-toggle" checked/> 3D zgrade · ZG3D 2022</label><label><input type="checkbox" id="projects-toggle" checked/> Gradski zahvati</label><label><input type="checkbox" id="bike-toggle"/> Biciklističke staze</label><label><input type="checkbox" id="network-toggle" checked/> Dostupna pješačka mreža</label></div>
  <div class="selection-card"><span class="selection-icon">${icon('map-pin')}</span><div><small>TVOJA POLAZNA TOČKA</small><strong id="location-name">Trg Petra Svačića</strong><span id="location-district">Donji grad, Zagreb</span></div><button id="recenter-button" aria-label="Vrati kartu na polaznu točku">${icon('locate-fixed')}</button></div>
  <div class="map-legend"><span><i class="legend-area"></i>Zona do <b id="legend-minutes">10</b> min hoda*</span><span><i class="legend-project"></i>Gradski zahvat</span><button id="legend-info" aria-label="Točnost zone hoda">${icon('info')}</button></div>
  <div class="map-status" id="map-status" role="status"><span class="spinner"></span>Učitavanje Zagreba…</div>
  <div class="detail-card" id="detail-card" hidden></div>
 </section>
</main>
<dialog id="dialog"><div id="dialog-content"></div></dialog><div class="toast" id="toast" role="status" hidden></div>`;
refreshIcons();
function toast(message:string){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,5500);}
function modal(content:string,wide=false){const d=$<HTMLDialogElement>('dialog');modalFocus=document.activeElement as HTMLElement;d.classList.toggle('wide',wide);$('dialog-content').innerHTML=`<button class="modal-close icon-button" aria-label="Zatvori prozor">${icon('x')}</button>${content}`;d.showModal();d.querySelector('.modal-close')!.addEventListener('click',()=>d.close());refreshIcons();}
$('dialog').addEventListener('click',e=>{if(e.target===$('dialog'))$<HTMLDialogElement>('dialog').close();});
$('dialog').addEventListener('close',()=>modalFocus?.focus());
function sourceModal(){if(!sources)return toast('Izvori se još učitavaju.');modal(`<span class="eyebrow">TRANSPARENTNO, OD IZVORA DO KARTE</span><h2>Grad otvorenih podataka.</h2><p>Glavni izvor je <a href="https://data.zagreb.hr/" target="_blank" rel="noopener">Portal otvorenih podataka Grada Zagreba</a>. Ovo je neovisni prototip, a ne službena gradska aplikacija.</p><div class="source-stats"><span><b>${number(sources.buildings)}</b>zapisa ZG3D modela</span><span><b>${number(amenities.length)}</b>javnih sadržaja</span><span><b>${number(projects.filter(p=>p.source==='komunalne_aktivnosti').length)}</b>komunalnih aktivnosti</span></div><div class="notice">Lokalna snimka preuzeta ${new Date(sources.retrieved).toLocaleDateString('hr-HR')} Podaci se ne osvježavaju uživo. ZG3D prikazuje detaljne krovne plohe LoD 2.2 pri približavanju, uz jednostavnije modele izdaleka. Trodimenzionalni reljef procijenjen je iz kota dna zgrada na mreži od 200 m; na neizgrađenim područjima, uključujući Medvednicu, interpolacija je gruba. Nije službeni digitalni model terena.</div><h3>Što treba znati</h3><p>Lokacije sadržaja ne jamče slobodna mjesta, radno vrijeme ni pristupačan ulaz. Dio parkova i mreža za hodanje dolaze iz OpenStreetMapa (ODbL). Glavni slojevi Grada koriste Otvorenu dozvolu.</p><p>Iznosi komunalnih aktivnosti su objavljene vrijednosti, ne potvrđeno potrošeni novac. Faza „Ugovaranje” sa statusom „Gotovo” prikazuje se kao planirano, jer završetak radova nije potvrđen. Kapitalni plan za 2024. je odvojena arhiva, bez izmišljenog aktualnog statusa. ${sources.districtLevelProjects} aktivnosti odnosi se na cijelu četvrt i prikazuje se samo u pregledu četvrti. ${sources.unlocatedProjects} zapisa nema valjanu lokaciju i nije na karti.</p><div class="sources-list">${Object.entries(sources.sources).map(([key,s]:[string,any])=>`<a href="${esc(s.url)}" target="_blank" rel="noopener"><span><strong>${esc(s.title)}</strong><small>${key==='osm'?'Dopunski izvor · ODbL':'Grad Zagreb'} · izmjena ${s.modified?new Date(s.modified).toLocaleDateString('hr-HR'):'nije objavljena'}</small></span>${icon('arrow-up-right')}</a>`).join('')}</div>`,true);}
function methodModal(){modal(`<span class="eyebrow">METODOLOGIJA · EKSPERIMENTALNO</span><h2>Blizina koja se može objasniti.</h2><h3>Vrijeme hoda</h3><p>Računamo najkraći put po preuzetoj pješačkoj mreži OpenStreetMapa brzinom 4,8 km/h (80 m/min). Na karti je radi čitljivosti najviše 55 oznaka sadržaja; puni popis ostaje u kategorijama. Polazište i sadržaje povezujemo s najbližim čvorom do 100 m; duljina tih spojeva ulazi u izračun. Prikazana minuta zaokružena je naviše.</p><p>Pristup zgradi, ograda ili pravi ulaz nisu provjereni. Ne računamo čekanje na semaforu, nagib, stepenice ni privremene prepreke. Mreža pokriva ${'15,75–16,25° E; 45,64–45,98° N'}. Izvan nje ne izmišljamo put.</p><div class="notice">Plava površina je orijentacijski omotač dostupnih čvorova i može obuhvatiti nedostupne površine. Plave linije prikazuju dosegnutu mrežu. Brojevi sadržaja koriste udaljenost po mreži, a ne taj omotač.</div><h3>Eksperimentalni indeks 0–100</h3><p>Indeks je udio dostupnih kategorija u odabranom pogledu. Svaka kategorija ima jednaku težinu i smatra se dostupnom ako barem jedan njezin sadržaj ima izračunati put unutar odabranog vremena. Ne mjeri kvalitetu, kapacitet, cijenu ni ukupan standard života.</p><p><b>Svi sadržaji:</b> svih 10 kategorija. <b>Obitelj:</b> vrtići, škole, zdravstvo, parkovi i sport. <b>Bez auta:</b> prijevoz, zdravstvo, tržnice i kultura. <b>Biciklist:</b> biciklistička infrastruktura, parkovi, sport i javni zdenci. Svi pogledi i dalje računaju hodanje.</p><h3>Usporedba četvrti</h3><p>Eksperimentalna usporedba koristi prosjek indeksa za 20 deterministički uzorkovanih položaja ZG3D modela po četvrti (visina barem 2 m). To je ilustrativni uzorak modela, a ne reprezentativno istraživanje stanovnika. Nema ponderiranja prema stanovništvu, veličini kućanstva ili broju stanova. Lokacije bez spoja na mrežu izuzete su i iskazuje se pokrivenost uzorka. Iznosi su zbroj objavljenih komunalnih aktivnosti koje nisu označene završenim radovima; kapitalni plan 2024. je isključen.</p>`);}
function helpModal(){modal(`<span class="eyebrow">DOBRO DOŠAO U MOJ ZAGREB</span><h2>Klikni gdje živiš.</h2><div class="help-step"><b>01</b><div><h3>Odaberi svoje polazište</h3><p>Klikni zgradu ili tlo na karti, pretraži ulicu ili upotrijebi svoju lokaciju. Lokacija se obrađuje u tvojem pregledniku.</p></div></div><div class="help-step"><b>02</b><div><h3>Istraži u 5, 10 ili 15 minuta</h3><p>Promijeni vrijeme hoda i osobni pogled. Klikni kategoriju za popis sadržaja, a sadržaj za detalje i prikaz puta.</p></div></div><div class="help-step"><b>03</b><div><h3>Otkrij što se mijenja</h3><p>Narančaste oznake su komunalni zahvati. Pogled „Grad u mom kvartu” prikazuje detalje, faze i objavljene vrijednosti.</p></div></div><p class="notice">Kotačić približava kartu. Desna tipka miša i povlačenje okreću i naginju prikaz. Tipka 3D / 2D mijenja perspektivu. Na dodirnom zaslonu koristi dva prsta.</p>`);}
['sources-button','snapshot-button'].forEach(id=>$(id).onclick=sourceModal);
['method-button','profile-info','legend-info'].forEach(id=>$(id).onclick=methodModal);
$('help-button').onclick=helpModal;
$('dismiss-tip').onclick=()=>$('map-instruction').hidden=true;
$('mobile-menu').onclick=()=>$('sidebar').classList.toggle('mobile-open');
$('search').addEventListener('input',search);$('search').addEventListener('focus',search);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('sidebar').classList.add('mobile-open');$('search').focus();}if(e.key==='Escape'){$('search-results').hidden=true;$('search').setAttribute('aria-expanded','false');$('detail-card').hidden=true;}});
document.addEventListener('click',e=>{if(!(e.target as HTMLElement).closest('.search-wrap')){$('search-results').hidden=true;$('search').setAttribute('aria-expanded','false');}});
function search(){const q=normalize($<HTMLInputElement>('search').value.trim());const box=$('search-results');if(q.length<2){box.hidden=true;$('search').setAttribute('aria-expanded','false');return;}
 const entries=[...districts.features.map(f=>({name:f.properties!.name,coordinates:f.properties!.center,type:'Gradska četvrt'})),...amenities.map(a=>({name:a.name,coordinates:a.coordinates,type:a.address||categories.find(c=>c.id===a.category)!.name})),...streets];
 const matches=entries.filter(e=>normalize(e.name+' '+e.type).includes(q)).slice(0,8);box.innerHTML=matches.length?matches.map((r,i)=>`<button role="option" id="search-option-${i}" data-result="${i}">${icon('map-pin')}<span><strong>${esc(r.name)}</strong><small>${esc(r.type)}</small></span>${icon('arrow-up-right')}</button>`).join(''):'<div class="empty-state">Nema rezultata u učitanim ulicama i sadržajima. Odaberi lokaciju na karti.</div>';box.hidden=false;$('search').setAttribute('aria-expanded','true');box.querySelectorAll<HTMLElement>('[data-result]').forEach(b=>b.onclick=()=>{const r=matches[Number(b.dataset.result)];selectOrigin(r.coordinates,r.name,true);box.hidden=true;$('search').setAttribute('aria-expanded','false');$<HTMLInputElement>('search').value='';$('sidebar').classList.remove('mobile-open');});refreshIcons();
}
$('search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();$('search-results').querySelector<HTMLElement>('button')?.focus();}if(e.key==='Enter')$('search-results').querySelector<HTMLElement>('button')?.click();});
$('search-results').addEventListener('keydown',e=>{const bs=[...$('search-results').querySelectorAll<HTMLButtonElement>('button')];const i=bs.indexOf(document.activeElement as HTMLButtonElement);if(e.key==='ArrowDown'){e.preventDefault();bs[(i+1)%bs.length]?.focus();}if(e.key==='ArrowUp'){e.preventDefault();bs[(i-1+bs.length)%bs.length]?.focus();}});
const profileCategories:Record<string,string[]>={all:categories.map(c=>c.id),family:['nursery','school','health','park','sport'],carfree:['transport','health','market','culture'],bike:['bike','park','sport','water']};
document.querySelectorAll<HTMLElement>('[data-minutes]').forEach(b=>b.onclick=()=>{minutes=Number(b.dataset.minutes);document.querySelectorAll<HTMLElement>('[data-minutes]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});$('minutes-label').textContent=String(minutes);if($('legend-minutes'))$('legend-minutes').textContent=String(minutes);calculate();});
document.querySelectorAll<HTMLElement>('[data-profile]').forEach(b=>b.onclick=()=>{profile=b.dataset.profile!;activeCategories=new Set(profileCategories[profile]);selectedCategory=null;document.querySelectorAll<HTMLElement>('[data-profile]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});if(profile==='bike'){$<HTMLInputElement>('bike-toggle').checked=true;setVisibility('cycleways',true);}renderAvailability();renderMarkers();if(cityMode)cityOverview(cityMetric);});
function setView(next:string){view=next;['nearby','projects'].forEach(v=>{const b=$(v+'-tab');b.classList.toggle('active',v===next);b.setAttribute('aria-selected',String(v===next));});$('availability-section').hidden=next!=='nearby';$('score-card').hidden=next!=='nearby';$('project-list-panel').hidden=next!=='projects';document.querySelector<HTMLElement>('.profile-section')!.hidden=next!=='nearby';renderProjects();renderMarkers();}
$('nearby-tab').onclick=()=>setView('nearby');$('projects-tab').onclick=()=>setView('projects');
function renderAvailability(){
 const counts:Record<string,number>={};for(const a of amenities)if(result?.distances[a.id]!==undefined)counts[a.category]=(counts[a.category]||0)+1;
 const total=amenities.filter(a=>activeCategories.has(a.category)&&result?.distances[a.id]!==undefined).length;
 $('amenity-total').textContent=result?`${total} lokacija`:'Računamo…';
 $('categories').innerHTML=categories.map(c=>`<div class="category-row ${activeCategories.has(c.id)?'enabled':'disabled'} ${selectedCategory===c.id?'expanded':''}"><button class="category-main" data-category="${c.id}" aria-expanded="${selectedCategory===c.id}"><span class="category-icon" style="--category-color:${c.color}">${icon(c.icon)}</span><span>${c.name}</span><b>${result?(counts[c.id]||0):'—'}</b>${icon('chevron-right')}</button><button class="layer-switch ${activeCategories.has(c.id)?'on':''}" data-toggle-category="${c.id}" role="switch" aria-checked="${activeCategories.has(c.id)}" aria-label="Prikaži ${c.name} na karti"><span></span></button></div>`).join('');
 $('categories').querySelectorAll<HTMLElement>('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=selectedCategory===b.dataset.category?null:b.dataset.category!;if(selectedCategory)activeCategories.add(selectedCategory);renderAvailability();renderMarkers();if(selectedCategory)$('amenity-list').scrollIntoView({block:'start',behavior:'smooth'});});
 $('categories').querySelectorAll<HTMLElement>('[data-toggle-category]').forEach(b=>b.onclick=()=>{const id=b.dataset.toggleCategory!;activeCategories.has(id)?activeCategories.delete(id):activeCategories.add(id);renderAvailability();renderMarkers();});
 const list=$('amenity-list');list.hidden=!selectedCategory;
 if(selectedCategory){const c=categories.find(c=>c.id===selectedCategory)!;const items=amenities.filter(a=>a.category===selectedCategory&&result?.distances[a.id]!==undefined).sort((a,b)=>result!.distances[a.id]-result!.distances[b.id]);list.innerHTML=`<div class="section-heading"><h3>${c.name}</h3><button class="text-button" id="close-category">Zatvori ${icon('x')}</button></div>${items.length?items.map(a=>`<button class="amenity-result" data-amenity="${esc(a.id)}"><span><strong>${esc(a.name)}</strong><small>${esc(a.address||a.detail)}</small></span><b>${result!.distances[a.id]}<small>min</small></b></button>`).join(''):'<p class="empty-state">Nema evidentiranih lokacija s izračunatim putem unutar odabranog vremena. To ne znači da sadržaj ne postoji.</p>'}`;$('close-category').onclick=()=>{selectedCategory=null;renderAvailability();renderMarkers();};list.querySelectorAll<HTMLElement>('[data-amenity]').forEach(b=>b.onclick=()=>showAmenity(amenities.find(a=>a.id===b.dataset.amenity)!));}
 const cats=profileCategories[profile],score=Math.round(cats.filter(c=>counts[c]>0).length/cats.length*100);
 $('score-value').innerHTML=`${result?.connected?score:'—'}<span>/ 100</span>`;$('score-title').textContent=!result?'Računamo dostupnost':!result.connected?'Nema veze s mrežom':score>=80?'Puno toga ti je blizu':score>=50?'Dobar dio dana, blizu tebe':'Istraži širu okolinu';$('score-description').textContent=result?.connected?`${cats.filter(c=>counts[c]>0).length} od ${cats.length} kategorija u ${minutes} min hoda.`:!result?'Izračun po mreži javnih putova.':'Odaberi lokaciju uz javni put.';$('score-bar').style.width=(result?.connected?score:0)+'%';refreshIcons();
}
function nearbyProjects(){return projects.filter(p=>p.coordinates&&p.locationPrecision!=='district'&&(includeArchive||p.source==='komunalne_aktivnosti')&&meters(origin,p.coordinates)<=minutes*80&&(statusFilter==='all'||p.status===statusFilter)).sort((a,b)=>meters(origin,a.coordinates!)-meters(origin,b.coordinates!));}
function projectCard(p:Project){return `<button class="project-row" data-project="${esc(p.id)}"><span class="project-line-icon ${p.status}">${icon(p.status==='completed'?'check-check':'construction')}</span><span><span class="status-label ${p.status}">${statusNames[p.status]}</span><strong>${esc(p.address||'Lokacija nije navedena')}</strong><small>${esc(p.name)}</small></span>${icon('chevron-right')}</button>`;}
function renderProjects(){const districtRecords=projects.filter(p=>p.locationPrecision==='district'&&p.district===districtAt(origin)?.id&&(statusFilter==='all'||p.status===statusFilter));const near=nearbyProjects(),active=near.filter(p=>p.status==='active').length;const float=$('projects-float');float.hidden=!showProjects||cityMode;float.innerHTML=`<div class="float-heading"><span class="orange-icon">${icon('construction')}</span><h2>Što se mijenja u blizini?</h2><span class="count-pill">${near.length}</span></div><p class="float-subtitle">Gradski zahvati oko tvog polazišta</p>${near.slice(0,3).map(projectCard).join('')}${!near.length?'<p class="empty-state">U ovoj blizini nema objavljenih zahvata za odabrani filtar.</p>':''}<button class="float-footer" id="all-projects">Istraži sve zahvate ${icon('arrow-right')}</button>`;
 const panel=$('project-list-panel');panel.innerHTML=`<div class="section-heading"><h2>Grad u tvom kvartu</h2><span class="count-pill">${near.length}</span></div><p class="muted small">Zahvati u krugu ${minutes*80} m. Udaljenost projekata je zračna.</p><div class="project-filters">${['all','planned','active','completed','stalled'].map(s=>`<button class="${statusFilter===s?'active':''}" data-status="${s}">${s==='all'?'Sve':statusNames[s]}</button>`).join('')}</div><label class="archive-check"><input type="checkbox" id="archive-check" ${includeArchive?'checked':''}/> Uključi kapitalni plan 2024. (arhiva)</label><div class="investment-summary"><div><span>Objavljene vrijednosti</span><strong>${compactMoney(near.reduce((s,p)=>s+(p.value||0),0))}</strong></div><div><span>U tijeku</span><strong>${active}<small> zahvata</small></strong></div></div><p class="muted small">Vrijednosti aktivnosti, ne potvrđeni rashodi.</p>${near.length?near.map(projectCard).join(''):'<div class="empty-state">Nema zahvata za ovaj odabir. Proširi vrijeme ili odaberi drugo polazište.</div>'}${districtRecords.length?`<div class="district-activities"><h3>Na razini cijele četvrti</h3><p class="muted small">${districtRecords.length} aktivnosti bez preciznog obuhvata. Nisu prikazane kao lokalne oznake.</p>${districtRecords.map(projectCard).join('')}</div>`:''}`;
 [float,panel].forEach(el=>el.querySelectorAll<HTMLElement>('[data-project]').forEach(b=>b.onclick=()=>showProject(projects.find(p=>p.id===b.dataset.project)!)));
 $('all-projects').onclick=()=>{setView('projects');$('sidebar').classList.add('mobile-open');};panel.querySelectorAll<HTMLElement>('[data-status]').forEach(b=>b.onclick=()=>{statusFilter=b.dataset.status!;renderProjects();renderMarkers();});$('archive-check').onchange=()=>{includeArchive=$<HTMLInputElement>('archive-check').checked;renderProjects();renderMarkers();};refreshIcons();}
function districtAt(c:Coord){return districts.features.find(f=>booleanPointInPolygon(point(c),f as any))?.properties as District|undefined;}
function selectOrigin(c:Coord,name?:string,fly=false){extras?.hideDetails();if(!dataReady)return;origin=c;const d=districtAt(c);districtName=d?.name||'Rubno područje';if(!name){const closest=streets.reduce<any>((a,s)=>!a||meters(c,s.coordinates)<meters(c,a.coordinates)?s:a,null);name=closest&&meters(c,closest.coordinates)<250?`Uz ${closest.name}`:'Odabrana lokacija';}locationName=name;cityMode=false;renderMapLegend();if(map?.getLayer('selected-building'))map.setFilter('selected-building',['==',['get','id'],-1]);$('location-name').textContent=name;$('location-district').textContent=districtName+', Zagreb';$('district-breadcrumb').textContent=districtName;$('detail-card').hidden=true;homeMarker?.setLngLat(c);setVisibility('district-fill',false);setVisibility('district-line',false);if(fly)map.flyTo({center:c,zoom:16,pitch:52,bearing:-22,duration:1200});calculate();updateUrl();}
function updateUrl(){const u=new URL(location.href);u.searchParams.set('lng',origin[0].toFixed(6));u.searchParams.set('lat',origin[1].toFixed(6));u.searchParams.set('min',String(minutes));history.replaceState({},'',u);}
function calculate(){if(!workerReady||!mapReady)return;result=null;requestId++;$('map-status').innerHTML=`<span class="spinner"></span>Počítamo dostupnost po pješačkoj mreži…`.replace('Počítamo','Računamo');$('map-status').hidden=false;worker.postMessage({type:'calculate',origin,minutes,id:requestId});renderAvailability();renderProjects();setData('route',empty);updateUrl();if(cityMode)cityOverview(cityMetric);}
function setData(id:string,data:any){(map?.getSource(id) as {setData:(data:any)=>void}|undefined)?.setData(data);}
function setVisibility(id:string,show:boolean){if(map?.getLayer(id))map.setLayoutProperty(id,'visibility',show?'visible':'none');}
function showAmenity(a:Amenity){extras?.hideDetails();$('detail-card').hidden=false;const time=result?.distances[a.id],cat=categories.find(c=>c.id===a.category)!;const source=sources.sources[a.source];$('detail-card').innerHTML=`<button class="detail-close icon-button" aria-label="Zatvori detalje">${icon('x')}</button><span class="detail-type" style="color:${cat.color}">${icon(cat.icon)}${cat.name}</span><h2>${esc(a.name)}</h2><p>${esc(a.address||'Adresa nije navedena')}</p>${a.detail?`<p class="muted">${esc(a.detail)}</p>`:''}<div class="detail-walk">${icon('footprints')}<strong>${time?time+' min hoda':'Izvan izračunate dostupnosti'}</strong><span>od tvog polazišta</span></div><a class="source-external" href="${esc(source.url)}" target="_blank" rel="noopener">Pogledaj izvorni skup ${icon('arrow-up-right')}</a><small class="muted">Lokacija u evidenciji ne jamči otvorenost, kapacitet ni pristupačnost ulaza.</small>`;bindDetail();if(time)worker.postMessage({type:'route',amenity:a.id,id:requestId});map.easeTo({center:a.coordinates,duration:650});}
function showProject(p:Project){extras?.hideDetails();$('detail-card').hidden=false;const source=sources.sources[p.source];$('detail-card').innerHTML=`<button class="detail-close icon-button" aria-label="Zatvori detalje">${icon('x')}</button><span class="status-label ${p.status}">${statusNames[p.status]}</span><h2>${esc(p.address||p.name)}</h2><p>${esc(p.name)}</p><dl><div><dt>Izvorna faza</dt><dd>${esc(p.phase||'Nije objavljena')}</dd></div><div><dt>Status aktivnosti u izvoru</dt><dd>${esc(p.rawStatus||'Nije objavljen')}</dd></div><div><dt>Objavljena vrijednost</dt><dd class="project-value">${money(p.value)}</dd></div><div><dt>Razdoblje izvođenja</dt><dd>${esc(p.period||'Nije objavljeno')}</dd></div><div><dt>Zadnja promjena zapisa</dt><dd>${esc(p.updated?.split(' ')[0]||'Nije objavljena')}</dd></div></dl><p class="notice small">${p.locationPrecision==='district'?'Zapis se odnosi na cijelu četvrt i nije vezan uz konkretnu lokaciju.':'Točka je lokacija iz izvora; ne predstavlja potvrđeni obuhvat zahvata.'} Vrijednost nije potvrda izvršenog plaćanja.</p><a class="source-external" href="${esc(source.url)}" target="_blank" rel="noopener">Provjeri službene podatke ${icon('arrow-up-right')}</a>`;bindDetail();if(p.coordinates&&p.locationPrecision!=='district')map.easeTo({center:p.coordinates,duration:650});setData('route',empty);}
function bindDetail(){$('detail-card').querySelector<HTMLElement>('.detail-close')!.onclick=()=>{$('detail-card').hidden=true;setData('route',empty);};refreshIcons();}
function renderMarkers(){if(!mapReady)return;extras?.update(origin,minutes,result);const keep=new Set<string>();if(cityMode||map.getZoom()<13){for(const marker of markers.values())marker.remove();markers.clear();return;}
 const items=amenities.filter(a=>activeCategories.has(a.category)&&(!selectedCategory||a.category===selectedCategory)&&result?.distances[a.id]!==undefined&&map.getBounds().contains(a.coordinates)).sort((a,b)=>meters(origin,a.coordinates)-meters(origin,b.coordinates)).slice(0,view==='nearby'?55:12);
 for(const a of items){const key='amenity:'+a.id;keep.add(key);if(markers.has(key))continue;const c=categories.find(c=>c.id===a.category)!;const el=document.createElement('button');el.className='poi-marker';el.style.setProperty('--pin',c.color);el.innerHTML=icon(c.icon);el.title=a.name;el.setAttribute('aria-label',a.name);el.onclick=e=>{e.stopPropagation();showAmenity(a);};el.dataset.markerKey=key;markers.set(key,new SceneMarker({element:el,anchor:'bottom',subpixelPositioning:true,rotationAlignment:'viewport',pitchAlignment:'viewport'}).setLngLat(a.coordinates).addTo(map));}
 if(showProjects){const ps=nearbyProjects().filter(p=>p.coordinates&&map.getBounds().contains(p.coordinates));const byLocation=new Map<string,Project[]>();for(const p of ps){const key=p.coordinates!.map(v=>v.toFixed(4)).join(',');const group=byLocation.get(key)||[];group.push(p);byLocation.set(key,group);}for(const ps of [...byLocation.values()].slice(0,55)){const p=ps[0];const key='project:'+ps.map(p=>p.id).sort().join('|');keep.add(key);if(markers.has(key))continue;const el=document.createElement('button');el.className='project-marker '+p.status;el.innerHTML=icon('construction')+(ps.length>1?`<b>${ps.length}</b>`:'');el.title=p.address;el.setAttribute('aria-label',`${statusNames[p.status]}: ${p.address}${ps.length>1?', '+ps.length+' aktivnosti':''}`);el.onclick=e=>{e.stopPropagation();if(ps.length===1)showProject(p);else{modal(`<span class="eyebrow">VIŠE AKTIVNOSTI NA LOKACIJI</span><h2>${esc(p.address)}</h2>${ps.map(projectCard).join('')}`);$('dialog-content').querySelectorAll<HTMLElement>('[data-project]').forEach(b=>b.onclick=()=>{$<HTMLDialogElement>('dialog').close();showProject(projects.find(p=>p.id===b.dataset.project)!);});}};el.dataset.markerKey=key;markers.set(key,new SceneMarker({element:el,anchor:'bottom',subpixelPositioning:true,rotationAlignment:'viewport',pitchAlignment:'viewport'}).setLngLat(p.coordinates!).addTo(map));}}
 for(const [key,marker] of markers){if(!keep.has(key)){marker.remove();markers.delete(key);}}
 refreshIcons();}
const districtIndex=(d:District)=>d.access?.[profile]?.[String(minutes)]??null;
function compareModal(){if(!dataReady)return toast('Četvrti se još učitavaju.');const rows=districts.features.map(f=>f.properties as District).sort((a,b)=>b.plannedValue-a.plannedValue);modal(`<span class="eyebrow">17 ČETVRTI · JEDAN ZAGREB</span><h2>Pogled na cijeli grad.</h2><p>Usporedi evidentirane sadržaje i objavljene komunalne vrijednosti. Odaberi četvrt za istraživanje pješice.</p><div class="compare-toggle"><button id="city-access" class="active">${icon('layers')}Dostupnost u ${minutes} min na karti</button><button id="city-investment">${icon('construction')}Komunalne vrijednosti na karti</button></div><div class="comparison-table"><table><thead><tr><th>Gradska četvrt</th><th>Indeks dostupnosti*</th><th>Lokacije</th><th>Radovi u tijeku</th><th>Komunalne vrijednosti*</th></tr></thead><tbody>${rows.map((d,i)=>`<tr data-district="${d.id}" tabindex="0" role="button" aria-label="Istraži ${esc(d.name)}"><td><small>${String(i+1).padStart(2,'0')}</small><strong>${esc(d.name)}</strong></td><td><div class="density-bar"><span style="width:${districtIndex(d)??0}%"></span><b>${districtIndex(d)??'—'}</b></div></td><td>${number(d.amenities)}</td><td>${d.projects?d.activeProjects:'—'}</td><td>${d.projects?compactMoney(d.plannedValue):'Nema zapisa'} ${icon('arrow-up-right')}</td></tr>`).join('')}</tbody></table></div><p class="notice small">*Zbroj objavljenih vrijednosti aktivnosti u pripremi, izvođenju ili zastoju. Nije ostvarena potrošnja ni ukupni proračun četvrti. Kapitalni plan 2024. nije uključen. Indeks dostupnosti je eksperimentalni prosjek za ${minutes} min hoda u odabranom osobnom pogledu. Uzorak je 20 položaja iz ZG3D skupa po četvrti; ne predstavlja sve stanovnike. Nepovezana polazišta izuzeta su iz prosjeka (Brezovica: 18/20, Sesvete: 19/20, ostale: 20/20).</p>`,true);$('dialog-content').querySelectorAll<HTMLElement>('[data-district]').forEach(b=>{const go=()=>{const d=rows.find(d=>d.id===b.dataset.district)!;$<HTMLDialogElement>('dialog').close();const local=amenities.filter(a=>a.district===d.id);const representative=local.sort((a,b)=>meters(a.coordinates,d.center)-meters(b.coordinates,d.center))[0];selectOrigin(representative?.coordinates||d.center,d.name,true);};b.onclick=go;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});$('city-access').onclick=()=>cityOverview('density');$('city-investment').onclick=()=>cityOverview('investment');}
function renderMapLegend(metric?:string){const el=document.querySelector<HTMLElement>('.map-legend')!;el.innerHTML=metric?`<span><i class="legend-area"></i>${metric==='density'?'Indeks dostupnosti: 0–100*':'Vrijednosti: 0–5+ mil. € · sivo: bez zapisa'}</span><button id="legend-info" aria-label="Metodologija usporedbe">${icon('info')}</button>`:`<span><i class="legend-area"></i>Zona do <b id="legend-minutes">${minutes}</b> min hoda*</span><span><i class="legend-project"></i>Gradski zahvat</span><button id="legend-info" aria-label="Točnost zone hoda">${icon('info')}</button>`;$('legend-info').onclick=methodModal;refreshIcons();}
function cityOverview(metric:string){$<HTMLDialogElement>('dialog').close();cityMode=true;cityMetric=metric;renderMapLegend(metric);setVisibility('district-fill',true);setVisibility('district-line',true);setData('districts',featureCollection(districts.features.map(f=>({...f,properties:{...f.properties,accessDisplay:districtIndex(f.properties as District)??0}}))));map.setPaintProperty('district-fill','fill-color',['case',metric==='investment'?['==',['get','projects'],0]:['==',1,0],'#d8dde3',['interpolate',['linear'],metric==='density'?['get','accessDisplay']:['get','plannedValue'],0,'#d9e6f6',metric==='density'?50:1500000,'#78a2e5',metric==='density'?100:5000000,'#2457c8']]);map.fitBounds(bbox(districts) as [number,number,number,number],{pitch:0,bearing:0,padding:55,duration:1200});$('district-breadcrumb').textContent=metric==='density'?`Indeks u ${minutes} min · eksperimentalno`:'Komunalne vrijednosti · svih 17 četvrti';$('projects-float').hidden=true;renderMarkers();toast('Klikni četvrt za detalje. Tamnija plava označava veću vrijednost.');}
['compare-nav','district-link','district-picker'].forEach(id=>$(id).onclick=compareModal);$('explore-nav').onclick=()=>selectOrigin(origin,locationName,true);
$('mountain-view').onclick=()=>map.flyTo({center:[15.96,45.87],zoom:12.7,pitch:65,bearing:0,duration:1600});
$('layers-button').onclick=()=>$('layers-panel').hidden=!$('layers-panel').hidden;
$('zoom-in').onclick=()=>map?.zoomIn();$('zoom-out').onclick=()=>map?.zoomOut();$('north-button').onclick=()=>map?.easeTo({bearing:0,duration:500});$('recenter-button').onclick=()=>selectOrigin(origin,locationName,true);
$('dimension-button').onclick=()=>{const flat=$('dimension-button').textContent==='3D';map.easeTo({pitch:flat?0:52,bearing:flat?0:-22,duration:650});$('dimension-button').textContent=flat?'2D':'3D';$('dimension-button').setAttribute('aria-label',flat?'Prebaci na 3D prikaz':'Prebaci na 2D prikaz');};
$('locate-button').onclick=()=>{if(!navigator.geolocation)return toast('Preglednik ne podržava lokaciju.');toast('Čekamo dopuštenje preglednika za tvoju lokaciju…');navigator.geolocation.getCurrentPosition(pos=>{const c:Coord=[pos.coords.longitude,pos.coords.latitude];if(!districtAt(c))return toast('Tvoja lokacija nije u obuhvatu Grada Zagreba. Odaberi mjesto na karti.');selectOrigin(c,'Moja lokacija',true);},()=>toast('Lokacija nije dostupna ili nije dopuštena. Odaberi polazište na karti.'),{timeout:12000,maximumAge:60000});};
$('buildings-toggle').onchange=()=>{const checked=$<HTMLInputElement>('buildings-toggle').checked;setVisibility('buildings',checked);setVisibility('selected-building',checked);};
$('projects-toggle').onchange=()=>{showProjects=$<HTMLInputElement>('projects-toggle').checked;renderProjects();renderMarkers();};
$('bike-toggle').onchange=()=>setVisibility('cycleways',$<HTMLInputElement>('bike-toggle').checked);
$('network-toggle').onchange=()=>{const v=$<HTMLInputElement>('network-toggle').checked;['walk-lines','walk-area','walk-outline'].forEach(id=>setVisibility(id,v));};
async function getJson(file:string){const r=await fetch(asset('data/'+file+'.json'));if(!r.ok)throw Error('Nije moguće učitati '+file);return r.json();}
async function boot(){
 try{
  [amenities,projects,districts,sources,streets,buildIndex]=await Promise.all(['amenities','projects','districts','sources','search','buildings-index'].map(getJson));dataReady=true;
  const params=new URLSearchParams(location.search),lng=Number(params.get('lng')),lat=Number(params.get('lat'));if(params.has('lng')&&params.has('lat')&&Number.isFinite(lng)&&Number.isFinite(lat)&&districtAt([lng,lat])){origin=[lng,lat];locationName='Odabrana lokacija';districtName=districtAt(origin)!.name;const m=Number(params.get('min'));if([5,10,15].includes(m))minutes=m;}
  document.querySelectorAll<HTMLElement>('[data-minutes]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.minutes)===minutes);b.setAttribute('aria-pressed',String(Number(b.dataset.minutes)===minutes));});$('minutes-label').textContent=String(minutes);if($('legend-minutes'))$('legend-minutes').textContent=String(minutes);$('location-name').textContent=locationName;$('location-district').textContent=districtName+', Zagreb';$('district-breadcrumb').textContent=districtName;
  map=new SceneMap('map',{center:origin,zoom:15.35,pitch:49,bearing:-22});
  let mapErrorReported=false;map.on('error',()=>{if(!mapErrorReported){mapErrorReported=true;toast('Kartografska podloga djelomično je nedostupna. Provjeri internetsku vezu.');}});
  map.on('load',e=>{
   sources.buildings=e.manifest.ukupno_zgrada;
   mapReady=true;for(const id of ['buildings','walk-area','walk-lines','route'])map.addSource(id,{type:'geojson',data:empty});map.addSource('parks',{type:'geojson',data:asset('data/parks.json')});map.addSource('cycleways',{type:'geojson',data:asset('data/cycleways.json')});map.addSource('districts',{type:'geojson',data:districts});
   map.addLayer({id:'parks',type:'fill',source:'parks',paint:{'fill-color':'#b7cbb0','fill-opacity':.6}});
   map.addLayer({id:'district-fill',type:'fill',source:'districts',layout:{visibility:'none'},paint:{'fill-color':'#7b9fdf','fill-opacity':.6}});map.addLayer({id:'district-line',type:'line',source:'districts',layout:{visibility:'none'},paint:{'line-color':'#527cbb','line-width':2}});
   map.addLayer({id:'walk-area',type:'fill',source:'walk-area',paint:{'fill-color':'#6895f7','fill-opacity':.15}});map.addLayer({id:'walk-outline',type:'line',source:'walk-area',paint:{'line-color':'#5386e8','line-width':1.8,'line-dasharray':[3,3],'line-opacity':.65}});
   map.addLayer({id:'walk-lines',type:'line',source:'walk-lines',paint:{'line-color':'#729ae2','line-width':2.8,'line-opacity':.5}});
   map.addLayer({id:'cycleways',type:'line',source:'cycleways',layout:{visibility:'none'},paint:{'line-color':'#328d80','line-width':3,'line-dasharray':[2,1]}});
   map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':'#2359e6','line-width':5,'line-opacity':.95},layout:{'line-cap':'round','line-join':'round'}});
   const el=document.createElement('div');el.className='home-marker';el.innerHTML=`<div class="home-pin">${icon('map-pin')}</div><span>Moje polazište</span>`;homeMarker=new SceneMarker({element:el,anchor:'bottom',subpixelPositioning:true,rotationAlignment:'viewport',pitchAlignment:'viewport'}).setLngLat(origin).addTo(map);refreshIcons();
   extras=new ExtraLayers(map,origin,id=>{setData('route',empty);worker.postMessage({type:'route',amenity:id,id:requestId,extended:true});});
   map.on('click',e=>{if(extras?.handleClick([e.lngLat.lng,e.lngLat.lat]))return;if(cityMode){const f=map.queryRenderedFeatures(e.point,{layers:['district-fill']})[0];if(f){const d=f.properties;toast(`${d.name} · ${d.amenities} sadržaja · ${compactMoney(d.plannedValue)} komunalnih vrijednosti`);selectOrigin([e.lngLat.lng,e.lngLat.lat],d.name,true);}return;}const building=map.queryRenderedFeatures(e.point,{layers:['buildings']})[0];const c:Coord=building?pointOnFeature(building as any).geometry.coordinates as Coord:[e.lngLat.lng,e.lngLat.lat];selectOrigin(c);if(building)map.setFilter('selected-building',['==',['get','id'],building.properties.id]);});
   map.on('moveend',()=>{if(cityMode&&map.getZoom()>=14){const c=map.getCenter();selectOrigin([c.lng,c.lat]);}renderMarkers();});map.on('pitchend',()=>{const is3D=map.getPitch()>10;$('dimension-button').textContent=is3D?'3D':'2D';$('dimension-button').setAttribute('aria-label',is3D?'Prebaci na 2D prikaz':'Prebaci na 3D prikaz');});calculate();renderProjects();
  });
  worker=new Worker(new URL('./walking.worker.ts',import.meta.url),{type:'module'});worker.postMessage({type:'init'});
  worker.onmessage=({data})=>{if(data.type==='ready'){workerReady=true;calculate();}if(data.type==='error'){$('map-status').textContent='Izračun nije dostupan. Osvježi stranicu za ponovni pokušaj.';toast(data.message);}if(data.type==='result'&&data.id===requestId){result=data;let hull=data.hull.length>3?convex(featureCollection(data.hull.map((c:Coord)=>point(c)))):null;setData('walk-area',hull||empty);setData('walk-lines',featureCollection(data.lines.map((c:Coord[])=>({type:'Feature',geometry:{type:'LineString',coordinates:c},properties:{}}))));$('map-status').innerHTML=data.connected?`${icon('check')}Pješačka mreža · procjena dostupnosti`:'Nema javnog puta unutar 100 m. Odaberi drugo polazište.';if(data.boundary)$('map-status').textContent='Rub preuzete mreže · dostupnost može biti nepotpuna';renderAvailability();renderProjects();renderMarkers();}if(data.type==='routeError'&&data.id===requestId)toast(data.message);if(data.type==='route'&&data.extended&&data.id===requestId)toast(`Put do usluge: približno ${data.minutes} min hoda. Odabrana zona dostupnosti ostaje nepromijenjena.`);if(data.type==='route'&&data.id===requestId)setData('route',{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:data.coordinates}});};
  renderAvailability();renderProjects();
 }catch(e){$('map-status').innerHTML=`${icon('info')}Učitavanje nije uspjelo. <button id="retry">Pokušaj ponovno</button>`;$('retry').onclick=()=>location.reload();toast(String(e));refreshIcons();}
}
boot();
